### ISSUE TITLE
Drawer opening animation not working

### ISSUE THREAD

**Issue by joshmitch2000** [huntabyte/shadcn-svelte#1455]
### Describe the bug

When adding the Drawer component into my project and following the example set up, my drawer does not smoothly animate in like it does in the example. It does animate out however.

https://github.com/user-attachments/assets/a71978a5-1ae3-4af0-ba18-cb0a9a63ceb5

### Reproduction

Insert Drawer component as per shadcn-svelte docs (plus some extra stuff for my own use case)

```html
<script lang="ts">
  import * as Drawer from "./ui/drawer";
</script>

<Drawer.Root>
  <Drawer.Trigger asChild let:builder>
    <Button
      on:click={handleFetchRandomMeal}
      disabled={isLoading}
      class={isLoading ? "loading" : ""}
      builders={[builder]}
      variant="outline"
    >
      Find Random Meal
    </Button>
  </Drawer.Trigger>
  <Drawer.Content class="h-[80%] min-h-fit">
    <div class="mx-auto w-full max-w-sm">
      <Drawer.Header class="text-left">
        <Drawer.Title class="text-3xl mt-4 mb-7 text-center"></Drawer.Title>
        <Drawer.Description></Drawer.Description>
      </Drawer.Header>
      <Drawer.Footer>
        <Drawer.Close asChild let:builder>
          <Button builders={[builder]} variant="outline">Close</Button>
          <Button
            on:click={handleFetchRandomMeal}
            disabled={isLoading}
            class={isLoading ? "loading" : ""}
          >
            Generate Another Meal
          </Button>
        </Drawer.Close>
      </Drawer.Footer>
    </div>
  </Drawer.Content>
</Drawer.Root>
```

### System Info

```bash
System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M2
    Memory: 77.14 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.15.1/bin/npm
  Browsers:
    Chrome: 130.0.6723.92
    Edge: 130.0.2849.68
    Safari: 18.0.1
  npmPackages:
    bits-ui: ^0.21.16 => 0.21.16 
    svelte: ^5.1.6 => 5.1.6 
    vaul-svelte: ^0.3.2 => 0.3.2
```

### Severity

annoyance

**Comment by ieedan** [comment]
I can't seem to reproduce this issue:
https://stackblitz.com/edit/github-ecwwps?file=src%2Froutes%2F%2Bpage.svelte

Maybe its something in your `on:click` handler that is somehow preventing the behavior?

**Comment by milksense** [comment]
Same thing.

**Comment by milksense** [comment]
According to my observations, this problem has been fixed in [1.0.0-next.2](https://www.npmjs.com/package/vaul-svelte/v/1.0.0-next.2)

**Comment by joshmitch2000** [comment]
> I can't seem to reproduce this issue: https://stackblitz.com/edit/github-ecwwps?file=src%2Froutes%2F%2Bpage.svelte
> 
> Maybe its something in your `on:click` handler that is somehow preventing the behavior?

Removed the `on:click` handler but still not animating in unfortunately.

```
<Drawer.Root>
  <Drawer.Trigger asChild let:builder>
    <Button
      builders={[builder]}
      variant="outline"
    >
      Open Drawer
    </Button>
  </Drawer.Trigger>
  <Drawer.Content class="h-[80%] min-h-fit">
    <div class="mx-auto w-full max-w-sm">
      <Drawer.Header class="text-left">
        <Drawer.Title class="text-3xl mt-4 mb-7 text-center">Your random recipe</Drawer.Title>
        <Drawer.Description></Drawer.Description>
      </Drawer.Header>
      <Drawer.Footer>
        <Drawer.Close asChild let:builder>
          <Button builders={[builder]} variant="outline">Close</Button>
        </Drawer.Close>
      </Drawer.Footer>
    </div>
  </Drawer.Content>
</Drawer.Root>
```

**Comment by ieedan** [comment]
What are your vaul-svelte and bits-ui versions?

**Comment by joshmitch2000** [comment]
npmPackages:
    bits-ui: ^0.21.16 => 0.21.16 
    svelte: ^5.1.6 => 5.1.6 
    vaul-svelte: ^0.3.2 => 0.3.2

**Comment by joshmitch2000** [comment]
> According to my observations, this problem has been fixed in [1.0.0-next.2](https://www.npmjs.com/package/vaul-svelte/v/1.0.0-next.2)

This is correct. Works in the latest version :)

```
System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M2
    Memory: 87.39 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.15.1/bin/npm
  Browsers:
    Chrome: 130.0.6723.92
    Chrome Canary: 132.0.6823.0
    Edge: 130.0.2849.68
    Safari: 18.0.1
  npmPackages:
    bits-ui: ^1.0.0-next.46 => 1.0.0-next.46 
    svelte: ^5.1.11 => 5.1.11 
    vaul-svelte: ^1.0.0-next.2 => 1.0.0-next.2 
```
