### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by rizal-30** [huntabyte/shadcn-svelte#1961]
### Describe the bug

The bug happen when using DropdownMenu.Trigger from the latest shadcn-svelte UI components (which internally uses bits-ui).

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-ninfftcv?file=src%2Froutes%2F%2Bpage.svelte

### Logs

```bash
TypeError: Cannot read properties of undefined (reading 'opts')
    at eval (/home/projects/stackblitz-starters-ninfftcv/node_modules/bits-ui/dist/bits/menu/menu.svelte.js:902:23)
    at <instance_members_initializer> (/home/projects/stackblitz-starters-ninfftcv/node_modules/bits-ui/dist/bits/menu/menu.svelte.js:904:4)
    at new DropdownMenuTriggerState (/home/projects/stackblitz-starters-ninfftcv/node_modules/bits-ui/dist/bits/menu/menu.svelte.js:850:13)
    at useMenuDropdownTrigger (/home/projects/stackblitz-starters-ninfftcv/node_modules/bits-ui/dist/bits/menu/menu.svelte.js:1053:9)
    at Module.Menu_trigger (/home/projects/stackblitz-starters-ninfftcv/node_modules/bits-ui/dist/bits/menu/components/menu-trigger.svelte:27:71)
    at $$render_inner (/home/projects/stackblitz-starters-ninfftcv/src/lib/components/ui/dropdown-menu/dropdown-menu-trigger.svelte:19:38)
    at Module.Dropdown_menu_trigger (/home/projects/stackblitz-starters-ninfftcv/src/lib/components/ui/dropdown-menu/dropdown-menu-trigger.svelte:39:3)
    at eval (/home/projects/stackblitz-starters-ninfftcv/src/routes/+page.svelte:29:27)
    at eval (/home/projects/stackblitz-starters-ninfftcv/node_modules/bits-ui/dist/bits/menu/components/menu.svelte:41:14)
    at Floating_layer (/home/projects/stackblitz-starters-ninfftcv/node_modules/bits-ui/dist/bits/utilities/floating-layer/components/floating-layer.svelte:15:12)
```

### System Info

```bash
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/kit: ^2.16.0 => 2.21.1 
    bits-ui: ^1.5.3 => 1.5.3 
    svelte: ^5.0.0 => 5.31.1 
    tailwindcss: ^4.0.0 => 4.1.7
```

### Severity

blocking all usage of shadcn-svelte

**Comment by ieedan** [comment]
This is an issue with the latest version of Svelte. This was fixed in the latest version of `bits-ui` so just upgrade and it should work!

**Comment by rizal-30** [comment]
Hi, thanks for the response!

I’ve updated to the latest version of bits-ui and I’m also using the latest versions of svelte, @sveltejs/kit, and tailwindcss. However, I’m still encountering the same error:

TypeError: Cannot read properties of undefined (reading 'opts')
It happens when I use <DropdownMenu.Trigger> from shadcn-svelte together with bits-ui.

Let me know if there’s anything else I should check or configure. I’ve double-checked that all packages are up to date.

Thanks again!

**Comment by rizal-30** [comment]
It works with Svelte 5.30.2, but not with 5.31.1.
Thanks for the help

**Comment by ruizdiazever** [comment]
> This is an issue Svelte introduced in their latest release - for now the workaround is to downgrade to 5.30.2 until this is resolved and released [sveltejs/svelte#15960](https://github.com/sveltejs/svelte/issues/15960)

Dont work in my case, the problem suddenly appeared this morning during a build (no package has been updated for a month) but today it failed like this, here my error:

```bash
TypeError: Cannot read properties of undefined (reading 'opts')
    at /Users/ever/devel/berli/client/node_modules/.pnpm/bits-ui@1.5.3_svelte@5.32.1/node_modules/bits-ui/dist/bits/menu/menu.svelte.js:714:29
    at <instance_members_initializer> (/Users/ever/devel/berli/client/node_modules/.pnpm/bits-ui@1.5.3_svelte@5.32.1/node_modules/bits-ui/dist/bits/menu/menu.svelte.js:717:6)
    at new DropdownMenuTriggerState (/Users/ever/devel/berli/client/node_modules/.pnpm/bits-ui@1.5.3_svelte@5.32.1/node_modules/bits-ui/dist/bits/menu/menu.svelte.js:666:16)
    at useMenuDropdownTrigger (/Users/ever/devel/berli/client/node_modules/.pnpm/bits-ui@1.5.3_svelte@5.32.1/node_modules/bits-ui/dist/bits/menu/menu.svelte.js:1053:9)
    at Module.Menu_trigger (/Users/ever/devel/berli/client/node_modules/.pnpm/bits-ui@1.5.3_svelte@5.32.1/node_modules/bits-ui/dist/bits/menu/components/menu-trigger.svelte:18:45)
    at eval (/Users/ever/devel/berli/client/src/components/common/header/lang.svelte:27:27)
    at /Users/ever/devel/berli/client/node_modules/.pnpm/bits-ui@1.5.3_svelte@5.32.1/node_modules/bits-ui/dist/bits/menu/components/menu.svelte:39:19
    at Floating_layer (/Users/ever/devel/berli/client/node_modules/.pnpm/bits-ui@1.5.3_svelte@5.32.1/node_modules/bits-ui/dist/bits/utilities/floating-layer/components/floating-layer.svelte:10:18)
    at Module.Menu (/Users/ever/devel/berli/client/node_modules/.pnpm/bits-ui@1.5.3_svelte@5.32.1/node_modules/bits-ui/dist/bits/menu/components/menu.svelte:39:35)
    at $$render_inner (/Users/ever/devel/berli/client/src/components/common/header/lang.svelte:23:25)
```

**Comment by mihkuno** [comment]
@ruizdiazever it does work, your logs is showing `svelte@5.32.1`. 
In `package.json`, you have to explicitly set `"svelte": "^5.0.0",` to `"svelte": "5.30.2",` and try deleting `node_modules` if it persists

**Comment by ruizdiazever** [comment]
> [@ruizdiazever](https://github.com/ruizdiazever) it does work, your logs is showing `svelte@5.32.1`. In `package.json`, you have to explicitly set `"svelte": "^5.0.0",` to `"svelte": "5.30.2",` and try deleting `node_modules` if it persists

Works perfectly, thank you very much!

**Comment by nktvit** [comment]
Thank you so much guys. You saved me lots of time!

**Comment by valiantlynx** [comment]
thanks. you saved us

**Comment by huntabyte** [comment]
Should be fixed by updating svelte to the latest version!
